import type { Language } from './i18n'

export const pageCopy = {
  EN: {
    clients: {
      eyebrow: 'Client management',
      title: 'Clients',
      description: 'Pipeline, health score, pinned accounts, tags, archive and custom CRM fields.',
      pipeline: 'Pipeline',
      table: 'Table',
      visiblePipeline: 'Visible pipeline',
      filteredAccounts: 'Filtered accounts',
      pinned: 'Pinned',
      priorityClients: 'Priority clients',
      avgHealth: 'Avg health',
      activeAccounts: 'Active accounts',
      pipelineValue: 'Pipeline value',
      monthlyRetainers: 'Monthly retainers',
      searchPlaceholder: 'Search clients, tags, companies...',
      allStatus: 'All status',
      lead: 'Lead',
      active: 'Active',
      inactive: 'Inactive',
      showingArchived: 'Showing archived',
      activeOnly: 'Active only',
      leadPipeline: 'Lead pipeline',
      clientTable: 'Client table',
      modeHint: 'Move clients through stages or inspect them in table mode.',
      visible: 'visible',
      clients: 'clients',
      health: 'Health',
      restore: 'Restore',
      archive: 'Archive',
      noClients: 'No clients.',
      noClientsFound: 'No clients found.',
      name: 'Name',
      company: 'Company',
      status: 'Status',
      stage: 'Stage',
      monthly: 'Monthly',
      unpin: 'Unpin',
      pin: 'Pin',
      addClient: 'Add client',
      addClientHint: 'Create a tagged account with stage and status.',
      phone: 'Phone',
      monthlyValue: 'Monthly value',
      tagsPlaceholder: 'Tags, comma separated',
      saving: 'Saving...',
      saveClient: 'Save client',
      clientCreated: 'Client created',
      addedToPipeline: 'was added to the pipeline.',
      pipelineUpdated: 'Pipeline updated',
      movedTo: 'moved to',
      clientPinned: 'Client pinned',
      clientUnpinned: 'Client unpinned',
      clientArchived: 'Client archived',
      movedOut: 'moved out of active pipeline.',
      clientRestored: 'Client restored',
      activeAgain: 'is active again.',
      stageLabels: {
        new: 'New',
        qualified: 'Qualified',
        proposal: 'Proposal',
        negotiation: 'Negotiation',
        won: 'Won',
        paused: 'Paused',
      },
    },
    tasks: {
      eyebrow: 'Operations',
      title: 'Tasks',
      description: 'Kanban workflow with recurring tasks, subtasks, comments, tags, archive and saved views.',
      saveView: 'Save view',
      reset: 'Reset',
      visibleTasks: 'Visible tasks',
      savedFiltersReady: 'Saved filters ready',
      dueToday: 'Due today',
      smartWidget: 'Smart widget',
      recurring: 'Recurring',
      automationReady: 'Automation-ready',
      archived: 'Archived',
      cleanWorkspace: 'Clean workspace',
      searchPlaceholder: 'Search task, tag, client...',
      allPriorities: 'All priorities',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      showingArchived: 'Showing archived',
      activeOnly: 'Active only',
      todo: 'Todo',
      inProgress: 'In progress',
      done: 'Done',
      plannedWork: 'Planned work',
      activeDelivery: 'Active delivery',
      completed: 'Completed',
      unknownClient: 'Unknown client',
      general: 'General',
      noTasksHere: 'No tasks here.',
      noDescription: 'No description yet.',
      due: 'Due',
      notSet: 'not set',
      subtasks: 'Subtasks',
      addSubtask: 'Add subtask...',
      add: 'Add',
      comments: 'Comments',
      addComment: 'Add comment...',
      post: 'Post',
      restore: 'Restore',
      archive: 'Archive',
      quickAdd: 'Quick add',
      quickAddHint: 'Create tagged, recurring work in one flow.',
      taskTitle: 'Task title',
      taskDescription: 'Description',
      generalTask: 'General task',
      noRecurrence: 'no recurrence',
      daily: 'daily',
      weekly: 'weekly',
      monthly: 'monthly',
      tagsPlaceholder: 'Tags, comma separated',
      saving: 'Saving...',
      saveTask: 'Save task',
      taskCreated: 'Task created',
      taskMoved: 'Task moved',
      isNow: 'is now',
      taskArchived: 'Task archived',
      movedToArchive: 'moved to archive.',
      taskRestored: 'Task restored',
      subtaskAdded: 'Subtask added',
      commentAdded: 'Comment added',
      viewSaved: 'View saved',
      viewSavedMessage: 'Your task filters are stored locally.',
      viewReset: 'View reset',
      viewResetMessage: 'Saved task filters were cleared.',
    },
  },
  RO: {
    clients: {
      eyebrow: 'Management clienți',
      title: 'Clienți',
      description: 'Pipeline, scor de sănătate, conturi prioritare, tag-uri, arhivare și câmpuri CRM custom.',
      pipeline: 'Pipeline',
      table: 'Tabel',
      visiblePipeline: 'Pipeline vizibil',
      filteredAccounts: 'Conturi filtrate',
      pinned: 'Prioritari',
      priorityClients: 'Clienți prioritari',
      avgHealth: 'Sănătate medie',
      activeAccounts: 'Conturi active',
      pipelineValue: 'Valoare pipeline',
      monthlyRetainers: 'Abonamente lunare',
      searchPlaceholder: 'Caută clienți, tag-uri, companii...',
      allStatus: 'Toate statusurile',
      lead: 'Lead',
      active: 'Activ',
      inactive: 'Inactiv',
      showingArchived: 'Arhivate afișate',
      activeOnly: 'Doar active',
      leadPipeline: 'Pipeline lead-uri',
      clientTable: 'Tabel clienți',
      modeHint: 'Mută clienții între etape sau inspectează-i în modul tabel.',
      visible: 'vizibili',
      clients: 'clienți',
      health: 'Sănătate',
      restore: 'Restaurează',
      archive: 'Arhivează',
      noClients: 'Nu există clienți.',
      noClientsFound: 'Nu s-au găsit clienți.',
      name: 'Nume',
      company: 'Companie',
      status: 'Status',
      stage: 'Etapă',
      monthly: 'Lunar',
      unpin: 'Scoate prioritar',
      pin: 'Prioritizează',
      addClient: 'Adaugă client',
      addClientHint: 'Creează un cont cu tag-uri, etapă și status.',
      phone: 'Telefon',
      monthlyValue: 'Valoare lunară',
      tagsPlaceholder: 'Tag-uri, separate prin virgulă',
      saving: 'Se salvează...',
      saveClient: 'Salvează client',
      clientCreated: 'Client creat',
      addedToPipeline: 'a fost adăugat în pipeline.',
      pipelineUpdated: 'Pipeline actualizat',
      movedTo: 'mutat în',
      clientPinned: 'Client prioritar',
      clientUnpinned: 'Client scos din prioritare',
      clientArchived: 'Client arhivat',
      movedOut: 'a fost scos din pipeline-ul activ.',
      clientRestored: 'Client restaurat',
      activeAgain: 'este activ din nou.',
      stageLabels: {
        new: 'Nou',
        qualified: 'Calificat',
        proposal: 'Propunere',
        negotiation: 'Negociere',
        won: 'Câștigat',
        paused: 'Pauzat',
      },
    },
    tasks: {
      eyebrow: 'Operațiuni',
      title: 'Task-uri',
      description: 'Flux Kanban cu task-uri recurente, subtasks, comentarii, tag-uri, arhivare și view-uri salvate.',
      saveView: 'Salvează view',
      reset: 'Resetează',
      visibleTasks: 'Task-uri vizibile',
      savedFiltersReady: 'Filtre salvate pregătite',
      dueToday: 'Scadente azi',
      smartWidget: 'Widget inteligent',
      recurring: 'Recurente',
      automationReady: 'Pregătite pentru automatizare',
      archived: 'Arhivate',
      cleanWorkspace: 'Workspace curat',
      searchPlaceholder: 'Caută task, tag, client...',
      allPriorities: 'Toate prioritățile',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      showingArchived: 'Arhivate afișate',
      activeOnly: 'Doar active',
      todo: 'De făcut',
      inProgress: 'În progres',
      done: 'Finalizate',
      plannedWork: 'Lucru planificat',
      activeDelivery: 'Livrare activă',
      completed: 'Finalizate',
      unknownClient: 'Client necunoscut',
      general: 'General',
      noTasksHere: 'Nu există task-uri aici.',
      noDescription: 'Fără descriere încă.',
      due: 'Termen',
      notSet: 'nesetat',
      subtasks: 'Subtask-uri',
      addSubtask: 'Adaugă subtask...',
      add: 'Adaugă',
      comments: 'Comentarii',
      addComment: 'Adaugă comentariu...',
      post: 'Postează',
      restore: 'Restaurează',
      archive: 'Arhivează',
      quickAdd: 'Adaugă rapid',
      quickAddHint: 'Creează lucru cu tag-uri și recurență într-un singur flux.',
      taskTitle: 'Titlu task',
      taskDescription: 'Descriere',
      generalTask: 'Task general',
      noRecurrence: 'fără recurență',
      daily: 'zilnic',
      weekly: 'săptămânal',
      monthly: 'lunar',
      tagsPlaceholder: 'Tag-uri, separate prin virgulă',
      saving: 'Se salvează...',
      saveTask: 'Salvează task',
      taskCreated: 'Task creat',
      taskMoved: 'Task mutat',
      isNow: 'este acum',
      taskArchived: 'Task arhivat',
      movedToArchive: 'a fost mutat în arhivă.',
      taskRestored: 'Task restaurat',
      subtaskAdded: 'Subtask adăugat',
      commentAdded: 'Comentariu adăugat',
      viewSaved: 'View salvat',
      viewSavedMessage: 'Filtrele task-urilor sunt salvate local.',
      viewReset: 'View resetat',
      viewResetMessage: 'Filtrele salvate au fost șterse.',
    },
  },
} as const

export function getPageCopy(language: Language) {
  return pageCopy[language]
}
