import { useMemo, useState } from 'react'
import { readSuiteCollection, updateSuiteItem, writeSuiteCollection, type NotificationItem } from '../lib/suiteStorage'
import { useLanguage } from '../lib/i18n'

export function NotificationsPage() {
  const { language } = useLanguage()
  const ro = language === 'RO'
  const [items, setItems] = useState<NotificationItem[]>(() => readSuiteCollection('notifications'))
  const unread = useMemo(() => items.filter((item) => !item.read).length, [items])

  function refresh() {
    setItems(readSuiteCollection('notifications'))
  }

  function markRead(item: NotificationItem) {
    updateSuiteItem('notifications', item.id, { read: true })
    refresh()
  }

  function markAllRead() {
    writeSuiteCollection('notifications', items.map((item) => ({ ...item, read: true })))
    refresh()
  }

  return (
    <div className="grid">
      <div className="page-header">
        <div>
          <p className="eyebrow">{ro ? 'Notificări' : 'Notifications'}</p>
          <h1 className="page-title">{ro ? 'Inbox operațional' : 'Operational inbox'}</h1>
          <p className="muted">{ro ? 'Notificări generate local din reguli, facturi, bookings și statusuri.' : 'Local notifications generated by rules, invoices, bookings and statuses.'}</p>
        </div>
        <div className="toolbar">
          <span className="pill">{unread} unread</span>
          <button className="button secondary" onClick={markAllRead}>{ro ? 'Marchează toate citite' : 'Mark all read'}</button>
        </div>
      </div>

      <section className="card card-pad">
        <div className="list">
          {items.map((item) => (
            <article className="note" key={item.id}>
              <div className="card-title-row">
                <div>
                  <strong>{item.title}</strong>
                  <div className="small muted">{item.message}</div>
                </div>
                <span className={`badge ${item.read ? 'inactive' : 'active'}`}>{item.type}</span>
              </div>
              <div className="toolbar">
                <span className="small muted">{item.createdAt}</span>
                {!item.read ? <button className="button secondary" onClick={() => markRead(item)}>{ro ? 'Citit' : 'Mark read'}</button> : null}
              </div>
            </article>
          ))}
          {items.length === 0 ? <div className="empty-state">{ro ? 'Nu există notificări.' : 'No notifications yet.'}</div> : null}
        </div>
      </section>
    </div>
  )
}
